export const CATEGORY_MAP = {
  공원묘지: [
    { location: 'cheorwon', name: '철원 공원묘원', region: 'north' },
    { location: 'dongducheon', name: '동두천 공원묘원', region: 'north' },
    { location: 'ilsan', name: '일산 공원묘원', region: 'north' },
    { location: 'pocheon', name: '포천 공원묘원', region: 'north' },
    { location: 'yangju', name: '양주 공원묘원', region: 'north' },
    { location: 'maesan', name: '광주매산 공원묘원', region: 'south' },
    { location: 'neungpyeong', name: '광주능평 공원묘원', region: 'south' },
    { location: 'opo', name: '오포 공원묘원', region: 'south' },
    { location: 'paldang', name: '팔당 공원묘원', region: 'south' },
    { location: 'yangpyeong', name: '양평 공원묘원', region: 'south' },
    { location: 'yangsuri', name: '양평 양수리 공원묘원', region: 'south' },
    { location: 'yongin', name: '용인 공원묘원', region: 'south' },
  ],
  납골당: [
    { location: 'byeokje_a', name: '벽제 봉안당 A', region: 'north' },
    { location: 'byeokje_b', name: '벽제 봉안당 B', region: 'north' },
    { location: 'byeokje_buddhism', name: '벽제 불교 봉안당', region: 'north' },
    { location: 'byeokje_c', name: '벽제 봉안당 C', region: 'north' },
    { location: 'byeokje_christianity', name: '벽제 기독교 봉안당', region: 'north' },
    { location: 'dongducheon_christianity', name: '동두천 기독교 봉안당', region: 'north' },
    { location: 'gwangtan', name: '광탄 봉안당', region: 'north' },
    { location: 'ilsan_a', name: '일산 봉안당 A', region: 'north' },
    { location: 'ilsan_b', name: '일산 봉안당 B', region: 'north' },
    { location: 'ilsan_buddhism', name: '일산 불교 봉안당', region: 'north' },
    { location: 'namyangju', name: '남양주 봉안당', region: 'north' },
    { location: 'paju', name: '파주 봉안당', region: 'north' },
    { location: 'pocheon_buddhism', name: '포천 불교 봉안당', region: 'north' },
    { location: 'tongillo', name: '통일로 봉안당', region: 'north' },
    { location: 'yangju', name: '양주 봉안당', region: 'north' },
    { location: 'yangpyeong', name: '양평 봉안당', region: 'north' },
    { location: 'yeoncheon', name: '연천 봉안당', region: 'north' },
    { location: 'anseong', name: '안성 봉안당', region: 'south' },
    { location: 'bundang', name: '분당 봉안당', region: 'south' },
    { location: 'ganghwa', name: '강화 봉안당', region: 'south' },
    { location: 'giheung', name: '기흥 봉안당', region: 'south' },
    { location: 'gonjiam', name: '곤지암 봉안당', region: 'south' },
    { location: 'gwangju_buddhism', name: '광주 불교 봉안당', region: 'south' },
    { location: 'Incheon_buddhism_A', name: '인천 불교 봉안당 A', region: 'south' },
    { location: 'Incheon_buddhism_B', name: '인천 불교 봉안당 B', region: 'south' },
    { location: 'opo', name: '오포 봉안당', region: 'south' },
    { location: 'pyeongtaek', name: '평택 봉안당', region: 'south' },
    { location: 'uiwang', name: '의왕 봉안당', region: 'south' },
    { location: 'yatap', name: '야탑 봉안당', region: 'south' },
    { location: 'yongin', name: '용인 봉안당', region: 'south' },
  ],
  수목장: [
    { location: 'cheorwon', name: '철원 수목장', region: 'north' },
    { location: 'gimpo', name: '김포 수목장', region: 'north' },
    { location: 'ilsan_A', name: '일산 수목장 A', region: 'north' },
    { location: 'ilsan_B', name: '일산 수목장 B', region: 'north' },
    { location: 'jangheung', name: '장흥 수목장', region: 'north' },
    { location: 'pocheon', name: '포천 수목장', region: 'north' },
    { location: 'yangju', name: '양주 수목장', region: 'north' },
    { location: 'yeoncheon', name: '연천 수목장', region: 'north' },
    { location: 'anseong', name: '안성 수목장', region: 'south' },
    { location: 'bundang', name: '분당 수목장', region: 'south' },
    { location: 'giheung', name: '기흥 수목장', region: 'south' },
    { location: 'pyeongtaek', name: '평택 수목장', region: 'south' },
    { location: 'seojong', name: '서종 수목장', region: 'south' },
    { location: 'yangji', name: '양지 수목장', region: 'south' },
    { location: 'yangpyeong', name: '양평 수목장', region: 'south' },
    { location: 'yongin', name: '용인 수목장', region: 'south' },
    { location: 'yongin_buddhism', name: '용인 불교 수목장', region: 'south' },
  ],
}
